// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import SetMapController from "./set_map_controller.js"
application.register("set-map", SetMapController)

import ShowMapController from "./show_map_controller.js"
application.register("show-map", ShowMapController)
